### ISSUE TITLE
Vines Agent won't start

### ISSUE THREAD

**Issue by MyMoviespw** [negativecode/vines#43]
So, first of all this is the first issue i am reporting on an github repo, so please be patient with me ;)

i am using debian 7.6 on an proxmox openvz container.
everything is installed as told on getvines.org.

after installation and first start i have taken a look at the web interface, but it showed nothing.
the systems page showed an console and a button where i should choose an server (a few things to choose but nothing active)
but .... the pages: services, files and setup are as blank as a unprinted sheet of paper.
so i checked if the agent is active -> its not.

i tried to start it with "vines-agent start"
and it gave me this:

```
root@vm02:~# vines-agent init mydomain.pw 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require': cannot load such file -- active_support/core_ext/class/attribute (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from /var/lib/gems/1.9.1/gems/blather-0.8.8/lib/blather.rb:83:in `block in <top (required)>'
    from /var/lib/gems/1.9.1/gems/blather-0.8.8/lib/blather.rb:4:in `each'
    from /var/lib/gems/1.9.1/gems/blather-0.8.8/lib/blather.rb:4:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /var/lib/gems/1.9.1/gems/vines-agent-0.1.4/lib/vines/agent.rb:31:in `block in <top (required)>'
    from /var/lib/gems/1.9.1/gems/vines-agent-0.1.4/lib/vines/agent.rb:5:in `each'
    from /var/lib/gems/1.9.1/gems/vines-agent-0.1.4/lib/vines/agent.rb:5:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /var/lib/gems/1.9.1/gems/vines-agent-0.1.4/bin/vines-agent:5:in `<top (required)>'
    from /usr/local/bin/vines-agent:23:in `load'
    from /usr/local/bin/vines-agent:23:in `<main>'
```

if anyone has an idea how to fix this ... i will spend him an virtual beer ;)

**Comment by dgraham** [comment]
Looks like trouble loading the ActiveSupport gem. As a quick test, I just tried this with good results:

```
$ ruby -v
ruby 2.1.2 [x86_64-darwin13.0]

$ mkdir test
$ cd test
$ vi Gemfile

# Add contents to Gemfile.
source 'https://rubygems.org'
gem 'vines-agent'

$ bundle install --path .bundle/gems --binstubs bin
$ bin/vines-agent init mydomain.pw
$ cd mydomain.pw
$ ../bin/vines-agent start
```

Listing gem versions with `bundle list` shows

```
$ bundle list
Gems included by the bundle:
  * activesupport (4.1.6)
```

If you're still having trouble, open an issue on the https://github.com/negativecode/vines-agent repository.
